FROM debian:buster

RUN apt-get update && apt-get install -y rclone ca-certificates
RUN apt-get install -y --no-install-recommends docker.io docker-compose

COPY . /akb-backend
WORKDIR /akb-backend

RUN touch /akb-backend/secret.env

CMD ["sh", "-c", "/akb-backend/docker-entrypoint-backup.sh"]
