# Generated by Django 2.2.12 on 2020-08-09 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('oid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('simbadid', models.CharField(blank=True, max_length=256)),
                ('changed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=256, unique=True)),
                ('priority', models.IntegerField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='akb_tag_name_32e7bd_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['priority'], name='akb_tag_priorit_361b7a_idx'),
        ),
        migrations.AddField(
            model_name='object',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='object',
            name='tags',
            field=models.ManyToManyField(related_name='tagged_objects', to='akb.Tag'),
        ),
    ]
