# Generated by Django 2.2.12 on 2020-07-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.BigIntegerField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=256, unique=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='akb_tag_name_32e7bd_idx'),
        ),
        migrations.AddField(
            model_name='object',
            name='tags',
            field=models.ManyToManyField(related_name='tagged_objects', to='akb.Tag'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['oid'], name='akb_object_oid_c77fb7_idx'),
        ),
    ]
