# Generated by Django 2.2.12 on 2020-07-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='simbadid',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
