# Generated by Django 2.2.12 on 2020-07-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akb', '0003_tag_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='priority',
            field=models.IntegerField(unique=False),
        ),
    ]
