# Generated by Django 3.0.8 on 2020-08-06 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akb', '0005_tag_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='description',
        ),
        migrations.RemoveField(
            model_name='object',
            name='simbadid',
        ),
        migrations.RemoveField(
            model_name='object',
            name='tags',
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('simbadid', models.CharField(blank=True, max_length=256)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='akb.Object')),
                ('tags', models.ManyToManyField(related_name='tagged_revisions', to='akb.Tag')),
            ],
            options={
                'ordering': ['object', '-date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='revision',
            index=models.Index(fields=['date'], name='akb_revisio_date_a7987f_idx'),
        ),
    ]
